<?php
namespace Redefinitions\Components\Cli\Migration;

/**
 * Created by IntelliJ IDEA.
 * User: wir_wolf
 * Date: 20.05.16
 * Time: 17:23
 */

/**
 * Class MigrateController
 * @package Redefinitions\Components\Cli\Migration
 */
class MigrateController extends \yii\console\controllers\MigrateController
{
    /**
     * @param \yii\base\Action $action
     * @return bool
     */
    public function beforeAction($action) {
        if (isset(\Yii::$app->log->targets['cli'])) {
            \Yii::$app->log->targets['cli']->enabled = false;
        }

        if (isset(\Yii::$app->params['yii.migrations'])) {
            $this->migrationPath = \Yii::$app->params['yii.migrations'];
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}